### ISSUE TITLE
Other Minor Improvements

### ISSUE THREAD

**Issue by Riajyuu** [hanyizhao/NetSpeedMonitor#3]
1. ability to change fonts
2. ability to resize the window
3. ability to change to measurement (from K/s to M/s for example)
4. dock into the taskbar, just like some Chinese IME.

**Comment by hanyizhao** [comment]
1.	It will change measurement automatically. See Tool.cs#GetNetSpeedString().
2.	Now it has a system tray icon on the taskbar.
3.	It seems not very urgent to have ability to change fonts or resize the window. Because the purpose of this repository is to imitate another program. Thank you for your comments.
